# === Makefile.linux ===

CC = gcc
WARNINGS = -Werror
CFLAGS = -O0 -mavx2 -std=gnu17 $(WARNINGS)
INCLUDES = -Isrc
LDFLAGS = -lm -lX11 -lpng -ljpeg
SRC_DIR = src
BUILD_DIR = build
TARGET = $(BUILD_DIR)/Main

SRCS = $(wildcard $(SRC_DIR)/*.c)
OBJS = $(patsubst $(SRC_DIR)/%.c, $(BUILD_DIR)/%.o, $(SRCS))

all: $(BUILD_DIR) $(TARGET)

alldebug:
	$(CC) -g $(CFLAGS) $(INCLUDES) ./$(SRC_DIR)/Main.c -o ./$(TARGET) $(LDFLAGS) 

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

$(TARGET): $(SRCS)
	$(CC) $(CFLAGS) $(INCLUDES) $(SRCS) -o $(TARGET) $(LDFLAGS)

debug:
	gdb ./$(TARGET)

exe:
	./$(TARGET)

comp:
	riscv64-unknown-elf-gcc \
    	-march=rv32i \
    	-mabi=ilp32 \
    	-nostdlib \
    	-ffreestanding \
    	-T ./code/linker.ld \
    	./code/start.S \
    	./code/main.c \
    	-o ./bin/main.elf

clean:
	rm -rf $(BUILD_DIR)/*

do: clean all exe

dg: clean alldebug debug

# === Makefile.linux ===